---
# This playbook will install mysql and create db user and give permissions.
- name: contraseña root para MySQL
  debconf:
   name: mysql-server
   question: mysql-server/root_password
   value: "000000"
   vtype: password

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   # no entiendo para que utilizan estas librerias pero leo que son librerias de ubuntus
  #- libselinux-python
   #- libsemanage-python
   
- name: Create Mysql configuration file
  template: 
    src=my.cnf.j2 
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644
    owner: root
    group:root
 notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables

- name: Create Application Database
  login_user:root
  login_password:000000
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
